#!/bin/bash

gem build modelstack.gemspec          # build the gem
gem_name=`ls modelstack*.gem`         # get gem name
gem install $gem_name                 # install the gem
rm $gem_name                          # remove gem file

# test modelkit
cd example && modelstack
cd ..