#!/usr/bin/env ruby

puts `gem build modelstack.gemspec`   # build the gem
gem_name = `ls modelstack*.gem`       # get gem name
puts `gem install #{gem_name}`      # install the gem
puts `rm #{gem_name}`               # remove gem file

# test modelkit
puts `cd example && modelstack`